apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-2cpnpm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2cpnpm
  namespace: my-nginx-2cpnpm
  labels:
    name: nginx-2cpnpm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-2cpnpm
  template:
    metadata:
      namespace: my-nginx-2cpnpm
      labels:
        name: nginx-2cpnpm
    spec:
      containers:
      - name: nginx-2cpnpm
        image: nginx
        ports:
        - containerPort: 80

