apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: test-app-epdnwbqe
  namespace: wego-system
resources:
- app.yaml
- test-app-epdnwbqe-gitops-deploy.yaml
- test-app-epdnwbqe-gitops-source.yaml
